title: Debarun Das
logo: assets/img/self_copy.jpg
#description: text below image
<br><br>
<a href = "www.google.com">Google </a>
<br><br>
show_downloads: false
theme: jekyll-theme-minimal
skin: dark



